vouch:
  listen: unix:/fake/path/to/socket
  socket_mode: 0644

oauth:
  provider: indieauth
  client_id: http://vouch.github.io
  auth_url: https://indielogin.com/auth
  callback_url: http://vouch.github.io:9090/auth
